version: 2.1

jobs:
  build_ruby:
    docker:
      - image: ruby:latest

    steps:
      - checkout
      - run:
          name: Unit test
          command: ruby rice_cooker_test.rb

workflows:
  version: 2
  build_workflow:
    jobs:
      - build_ruby:
          filters:
            branches:
              only:
                - feature/ruby
